all:
  hosts:
    # localhost:
    #   ansible_connection: local
    kc1:
      ansible_host: 10.0.129.65
    kc2:
      ansible_host: 10.0.149.189
    kc3:
      ansible_host: 10.0.163.213
    kb1:
      ansible_host: 10.0.141.91
    kb2:
      ansible_host: 10.0.147.143
    kb3:
      ansible_host: 10.0.161.4
  vars:
    logscale_kafka_topic_prefix: g001
    # ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ec2-user@ec2-44-200-157-191.compute-1.amazonaws.com"'
    # ansible_user: ec2-user
  children:
    kafka:
      children:
        controllers:
          hosts:
            kc1:
              kafka_node_id: 101
            kc2:
              kafka_node_id: 102
            kc3:
              kafka_node_id: 103
          vars:
            kafka_node_roles:
              - controller
        brokers:
          hosts:
            kb1:
              kafka_node_id: 201
            kb2:
              kafka_node_id: 202
            kb3:
              kafka_node_id: 203
          vars:
            kafka_node_roles:
              - broker
      vars:
        # ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ec2-user@ec2-44-200-157-191.compute-1.amazonaws.com"'
        # ansible_user: ec2-user
        kafka_install_dependencies: true
        kafka__dependencies: "zulu17-jdk-headless-17.0.13-1"
        kafka_scala_version: 2.13
        kafka_version: 3.9.0
        kafka_heap_size: 2G #note sets -Xmx and -Xms
        kafka_opts:
        - -XX:NewSize=256m
        - -XX:MetaspaceSize=96m
        - -XX:+UseG1GC
        - -XX:MaxGCPauseMillis=20
        - -XX:InitiatingHeapOccupancyPercent=35
        - -XX:G1HeapRegionSize=16M
        - -XX:MinMetaspaceFreeRatio=50
        - -XX:MaxMetaspaceFreeRatio=80
        - -XX:+ExplicitGCInvokesConcurrent