all:
  hosts:
    controller1:
      ansible_host: 10.0.129.65
    controller2:
      ansible_host: 10.0.149.189
    controller3:
      ansible_host: 10.0.169.126
    broker1:
      ansible_host: 10.0.141.91
    broker2:
      ansible_host: 10.0.147.143
    broker3:
      ansible_host: 10.0.161.4
brokers:
  hosts:
    broker1:
      ansible_host: 10.0.141.91
      kafkaId: 101
    broker2:
      ansible_host: 10.0.147.143
      kafkaId: 102
    broker3:
      ansible_host: 10.0.161.4
      kafkaId: 103
  vars:
    kafkaControllerQuorumVoters: 1@10.0.129.65:9093,2@10.0.149.189:9093,3@10.0.169.126:9093
controllers:
  hosts:
    controller1:
      ansible_host: 10.0.129.65
      kafkaId: 1
    controller2:
      ansible_host: 10.0.149.189
      kafkaId: 2
    controller3:
      ansible_host: 10.0.169.126
      kafkaId: 3
  vars:
    kafkaControllerQuorumVoters: 1@10.0.129.65:9093,2@10.0.149.189:9093,3@10.0.169.126:9093
