all:
  hosts:
    kc1:
      ansible_host: 10.0.129.65
    kc2:
      ansible_host: 10.0.149.189
    kc3:
      ansible_host: 10.0.163.213
    kb1:
      ansible_host: 10.0.141.91
    kb2:
      ansible_host: 10.0.147.143
    kb3:
      ansible_host: 10.0.161.4
kafka:
  controllers:
    hosts:
      kc1:
        kafka_node_id: 101
      kc2:
        kafka_node_id: 102
      kc3:
        kafka_node_id: 103
    vars:
      kafka_node_roles:
        - controller
  brokers:
    hosts:
      kb1:
        kafka_node_id: 201
      kb2:
        kafka_node_id: 202
      kb3:
        kafka_node_id: 203
    vars:
      kafka_node_roles:
        - broker
