---
- name: Load Balancer
  hosts: lb
  become: true
  roles:
    - role: nginxinc.nginx
      nginx_service_modify: true
      nginx_service_timeout: 95
      nginx_logrotate_conf_enable: true
      nginx_logrotate_conf:
        paths: /var/log/nginx/*.log
        options:
          - daily
          - missingok
          - rotate 14
          - compress
          - delaycompress
          - notifempty
          - sharedscripts