---
- name: Load Balancer
  hosts: logscaleLB
  become: true
  roles:
    - role: nginxinc.nginx
      nginx_selinux: true
      nginx_service_modify: true
      nginx_service_timeout: 95
      nginx_logrotate_conf_enable: true
      nginx_logrotate_conf:
        paths: /var/log/nginx/*.log
        options:
          - daily
          - missingok
          - rotate 14
          - compress
          - delaycompress
          - notifempty
          - sharedscripts
          - postrotate
    - role: ansible-role-nginx-config
      nginx_config_selinux: true
      nginx_config_debug_output: true
      # nginx_config_upload_enable: true
      # nginx_config_upload:
      #   - src: ../common/files/snippets/location_snippet.conf
      #     dest: /etc/nginx/snippets
      #     backup: true
      #   - src: ../common/files/http/
      #     dest: /etc/nginx/conf.d
      #     backup: true      
      nginx_config_http_template_enable: true
      nginx_config_http_template:
        - template_file: ../templates/nginx/logscale.conf.j2
          deployment_location: /etc/nginx/conf.d/logscale.conf
          # config:
            cache_path:
              - path: /var/cache/nginx/proxy/logscale
                levels: "1:1"
                use_temp_path: false
                inactive: 10m
                keys_zone:
                  name: frontend_proxy_cache
                  size: 10m
                max_size: 2g
                min_free: 1g
                manager_files: 100
                manager_sleep: 500ms
                manager_threshold: 200ms
                loader_files: 100
                loader_sleep: 50ms
                loader_threshold: 200ms
                purger: false
                purger_files: 10
                purger_sleep: 50ms
                purger_threshold: 50ms            
            upstreams:
              - name: logscaleui
                least_conn: true
                servers: >
                  [ {% for v in groups["logscaleAllInOne"] %}
                    {
                      'address':'{{ hostvars[v].ansible_host }}:{{ logscale_port }}',
                      max_fails: 0,
                      fail_timeout: 10s,
                      max_conns: 256
                    }
                    {% if not loop.last %},{% endif %}
                    {% endfor %}
                  ]
            servers:
              - core:
                  listen:
                    - port: 80
                  server_name: ec2-44-200-157-191.compute-1.amazonaws.com
                log:
                  access:
                    - path: /var/log/nginx/access.log
                      format: main
                locations:
                  - location: /
                    proxy:
                      pass: http://logscaleui/
                      http_version: 1.1
                      set_header:
                        - field: X-Forwarded-Proto
                          value: $scheme
                        - field: X-Forwarded-For
                          value: $proxy_add_x_forwarded_for
                        - field: X-Real-IP
                          value: $remote_addr
                        - field: Host
                          value: $host
