- name: Kafka
  hosts: brokers,controllers
  become: true
  tasks:
    - name: Import azul key from a url
      ansible.builtin.rpm_key:
        state: present
        key: https://www.azul.com/wp-content/uploads/2021/05/0xB1998361219BD9C9.txt
      tags:
        - openjdk
    - name: Install the azul rpm from a remote repo
      ansible.builtin.dnf:
        name: "https://cdn.azul.com/zulu/bin/zulu-repo-1.0.0-1.noarch.rpm"
        state: present
      tags:
        - openjdk
    - name: Install the zulu-17 rpm from a remote repo
      
      ansible.builtin.dnf:
        name: zulu17-jdk == 17.0.13-1
        state: present
      tags:
        - openjdk
    - name: Add another bin dir to system-wide $PATH.
      ansible.builtin.copy:
        owner: root
        group: root
        dest: /etc/profile.d/azul.sh
        content: "PATH=$PATH:/usr/lib/jvm/zulu17/bin"
