- name: Kfaka 
  hosts: brokers,controllers
  become: true
  tasks:
    - name: Enable service kafka and ensure it is not masked
      ansible.builtin.systemd_service:
        name: kafka
        enabled: false
        masked: no
        state: stopped
    - name: delete kafka
      containers.podman.podman_container:
        name: kafka
        state: absent
    - name: delete a Quadlet file for a volume kafka-logs
      containers.podman.podman_volume:
        state: absent
        name: kafka-logs
    - name: delete a Quadlet file for a volume kafka-data
      containers.podman.podman_volume:
        state: absent
        name: kafka-data

