- name: Common Steps
  hosts: all
  tasks:
    - name: Install Podman
      become: true
      block:
        - name: Ensure Podman is installed
          ansible.builtin.dnf:
            name: podman
            state: present
      
- name: Kfaka Common
  hosts: brokers,controllers
  become: true
  tasks:
    - name: Create a Quadlet file for a volume kafka-logs
      containers.podman.podman_volume:
        state: absent
        name: kafka-logs
    - name: Create a Quadlet file for a volume kafka-data
      containers.podman.podman_volume:
        state: absent
        name: kafka-data

- name: Kafka Controllers
  hosts: controllers
  serial: 1
  become: true
  tasks:
    - name: kafka
      notify: Restart Kafka
      containers.podman.podman_container:
        name: kafka
        image: apache/kafka:3.9.0
        state: quadlet
        read_only: true
        read_only_tmpfs: true
        env:
          KAFKA_NODE_ID: "{{ kafkaId }}"
          KAFKA_PROCESS_ROLES: controller
          KAFKA_LISTENERS: CONTROLLER://:9093
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_CONTROLLER_QUORUM_VOTERS: "{{ kafkaControllerQuorumVoters }}"
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
          KAFKA_LOG_DIR: "/data"
          KAFKA_CLUSTER_ID: "{{ kafkaClusterID }}"
        ports:
          - "9093:9093"
        volumes:
          - "kafka-data:/data"
          - "kafka-logs:/opt/kafka/logs"
        # network: host
        tmpfs:
          "/opt/kafka/config": "rw,noexec,nosuid,nodev,tmpcopyup,mode=1777"
        quadlet_options:
          - |
            [Install]
            WantedBy=multi-user.target
    - name: Daemon Reload
      ansible.builtin.systemd_service:
        daemon_reload: true
    - name: Enable service kafka and ensure it is not masked
      ansible.builtin.systemd_service:
        name: kafka
        enabled: true
        masked: no
        state: started
  handlers:
    - name: Restart Kafka
      ansible.builtin.systemd_service:
        name: kafka
        state: restarted

- name: Kafka Brokers
  hosts: brokers
  become: true
  tasks:
    - name: kafka
      notify: Restart Kafka
      containers.podman.podman_container:
        name: kafka
        image: apache/kafka:3.9.0
        state: quadlet
        read_only: true
        read_only_tmpfs: true
        env:
          KAFKA_NODE_ID: "{{ kafkaId }}"
          KAFKA_PROCESS_ROLES: broker
          KAFKA_LISTENERS: "PLAINTEXT://:9091,PLAINTEXT_HOST://:9092"
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://{{ ansible_host }}:9091,PLAINTEXT_HOST://{{ ansible_host }}:9092"
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_CONTROLLER_QUORUM_VOTERS: "{{ kafkaControllerQuorumVoters }}"
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
          KAFKA_LOG_DIR: "/data"
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_CLUSTER_ID: "{{ kafkaClusterID }}"
        ports:
          - "9091:9091"
          - "9092:9092"
        volumes:
          - "kafka-data:/data"
          - "kafka-logs:/opt/kafka/logs"
        # network: host
        tmpfs:
          "/opt/kafka/config": "rw,noexec,nosuid,nodev,tmpcopyup,mode=1777"
        quadlet_options:
          - |
            [Install]
            WantedBy=multi-user.target
    - name: Daemon Reload
      ansible.builtin.systemd_service:
        daemon_reload: true
    - name: Enable service kafka and ensure it is not masked
      ansible.builtin.systemd_service:
        name: kafka
        enabled: true
        masked: no
        state: started
  handlers:
    - name: Restart Kafka
      ansible.builtin.systemd_service:
        name: kafka
        state: restarted
