- name: Add to known_hosts
  hosts: all
  tasks:
    - name: get port, default 22
      delegate_to: localhost
      set_fact:
        ansible_ssh_port: "{{ hostvars[inventory_hostname]['ansible_ssh_port'] | default('22') }}"
    - name: Ensure ssh host key known
      delegate_to: localhost
      lineinfile:
        dest: ~/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -trsa -p' + ansible_ssh_port + ' ' + ansible_ssh_host) }}"
- name: Common Steps
  hosts: all
  tasks:
    - name: Install Podman
      become: true
      block:
        - name: Ensure Podman is installed
          ansible.builtin.dnf:
            name: podman
            state: present
- name: Kafka Controllers
  hosts: controllers
  serial: 1
  become: true
  tasks:
    - name: Ensure group "kafka" exists
      ansible.builtin.group:
        name: kafka-controller
        gid: 10001
        state: present  
    - name: Create a user 'kafka' with a home directory
      ansible.builtin.user:
        name: kafka-controller
        create_home: yes
        system: true
        shell: /sbin/nologin
        uid: 10001
        group: kafka-controller
    - name: Create a Quadlet file for a volume
      containers.podman.podman_volume:
        state: quadlet
        name: kafkadata
    - name: kafka
      containers.podman.podman_container:
        name: kafka-controller
        image: apache/kafka:3.9.0
        state: quadlet
        # device: "/dev/sda:/dev/xvda:rwm"
        # network: host
        user: kafka-controller
        env:
          KAFKA_NODE_ID: "{{ kafkaId }}"
          KAFKA_PROCESS_ROLES: controller
          KAFKA_LISTENERS: CONTROLLER://:9093
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_CONTROLLER_QUORUM_VOTERS: "{{ kafkaControllerQuorumVoters }}"
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        # ports:
        #   - "8080:80"
        # volumes:
        #   - "kafkadata:/usr/share/nginx/html"
        # quadlet_options:
        #   - "AutoUpdate=registry"
        #   - "Pull=newer"
        #   - |
        #     [Install]
        #     WantedBy=default.target
    - name: Daemon Reload
      ansible.builtin.systemd_service:
        daemon_reload: true
    - name: Enable service kafka and ensure it is not masked
      ansible.builtin.systemd_service:
        name: kafka-controller
        enabled: true
        masked: no
        state: started
