---
- name: Common Steps
  hosts: all
  tasks:
    - name: Install Podman
      become: true
      block:
        - name: Ensure Podman is installed
          ansible.builtin.dnf:
            name: podman
            state: present
- name: Install Podman
  hosts: all
  tasks:
    - name: Install Podman
      become: true
      block:
        - name: Ensure Podman is installed
          ansible.builtin.dnf:
            name: podman
            state: present
